### PR TITLE
Fix SMHP config validator

### PR DESCRIPTION
**Pull request by verdimrc**
*Issue #, if available:* N/A

*Description of changes:* Read VpcConfig from a separate JSON file.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sean-smith** [comment]
Why not just read it from the cluster config? i.e.

```yaml
{
    "ClusterName": "ml-cluster",
    "InstanceGroups": [
      {
        "InstanceGroupName": "controller-machine",
        "InstanceType": "ml.m5.xlarge",
        "InstanceCount": 1,
        "LifeCycleConfig": {
          "SourceS3Uri": "s3://${BUCKET}/src",
          "OnCreate": "on_create.sh"
        },
        "ExecutionRole": "${ROLE}",
        "ThreadsPerCore": 1
      },
      {
        "InstanceGroupName": "worker-group-1",
        "InstanceType": "ml.trn1.32xlarge",
        "InstanceCount": 1,
        "LifeCycleConfig": {
          "SourceS3Uri": "s3://${BUCKET}/src",
          "OnCreate": "on_create.sh"
        },
        "ExecutionRole": "${ROLE}",
        "ThreadsPerCore": 1
      }
    ],
    "VpcConfig": {
      "SecurityGroupIds": ["$SECURITY_GROUP"],
      "Subnets":["$SUBNET_ID"]
    }
}
```

See https://catalog.workshops.aws/sagemaker-hyperpod/en-US/01-cluster/04-create-cluster

**Comment by verdimrc** [comment]
I was just following along the existing script which read from two config files.

**Comment by verdimrc** [comment]
Both ways have their own merits

- use-case A: to validate all config files before create-cluster. This the current validator implementation.
- use-case B: to validate an existing cluster -- all info red from the cluster (or S3 bucket, in the case of provisioning_parameter?).

**Comment by verdimrc** [comment]
It turns out there're two `create-cluster` styles:

1. Use a single JSON file: `aws sagemaker create-cluster --cli-input-json file://config-cluster.json ...`, and the JSON file is a dictionary. Ref: [AWS docs](https://docs.aws.amazon.com/sagemaker/latest/dg/smcluster-getting-started-cli.html), [SMHP workshop](https://catalog.workshops.aws/sagemaker-hyperpod/en-US/01-cluster/04-create-cluster).

2. Use multiple JSON files: `aws sagemaker create-cluster --instance-groups file://xxx.json --vpc-config file://yyy.json --cluster-name zzz`. Ref: [SMHP Readme in this repo](https://github.com/aws-samples/awsome-distributed-training/blob/f45ad0f1be57dfa2483d6df58debc47836c557cb/1.architectures/5.sagemaker-hyperpod/README.md).

The PR uses style 2, but the base implementation is style 1, so not compatible.

**Comment by sean-smith** [comment]
> It turns out there're two `create-cluster` styles:
> 
> 1. Use a single JSON file: `aws sagemaker create-cluster --cli-input-json file://config-cluster.json ...`, and the JSON file is a dictionary. Ref: [AWS docs](https://docs.aws.amazon.com/sagemaker/latest/dg/smcluster-getting-started-cli.html), [SMHP workshop](https://catalog.workshops.aws/sagemaker-hyperpod/en-US/01-cluster/04-create-cluster).
> 2. Use multiple JSON files: `aws sagemaker create-cluster --instance-groups file://xxx.json --vpc-config file://yyy.json --cluster-name zzz`. The instance-group JSON is a list, not a dictionary. Ref: [SMHP Readme in this repo](https://github.com/aws-samples/awsome-distributed-training/blob/f45ad0f1be57dfa2483d6df58debc47836c557cb/1.architectures/5.sagemaker-hyperpod/README.md).
> 
> This PR uses style 2, but the base implementation is style 1, so not compatible.

Yup, I don't like the seperate VPC info so I used the combined file in the workshop.

**Comment by verdimrc** [comment]
> Yup, I don't like the seperate VPC info so I used the combined file in the workshop.

Beware that update-cluster doesn't accept VpcConfig, so the same file can't be used for both create-cluster and update-cluster. @sean-smith

**Comment by sean-smith** [comment]
> > Yup, I don't like the seperate VPC info so I used the combined file in the workshop.
> 
> Beware that update-cluster doesn't accept VpcConfig, so the same file can't be used for both create-cluster and update-cluster. @sean-smith

Yup already saw that :) see https://catalog.workshops.aws/sagemaker-hyperpod/en-US/04-advanced/07-login-node

**Pull request closed without merging**
