### PR TITLE
Instantiate model on CPU on rank=0 only to prevent CPU OOM

### PR DESCRIPTION
**Pull request by pbelevich**
e.g. 70B * 4 bytes * 8 processes > 2T RAM available on P5

### CODE REVIEW

**Review by sean-smith — APPROVED** [review]
LGTM

**Review by KeitaW — APPROVED** [review]
LGTM. Thanks @pbelevich  for creating the PR.
Just a question for my future reference. 
in https://github.com/lchu-ibm/llama-recipes/blob/feaa344af3102d2dab840272e946abe93dd98afe/llama_finetuning.py#L152 they use `recurse=False` while in this PR you use `recurse=True`. Is there any difference in behavior because of this?

**Comment by pbelevich** [comment]
@KeitaW I went through FSDP code and I think that `recurse` should be `False`. Thanks for careful code-review! Btw, I suggested a fix for llama-recipes: https://github.com/meta-llama/llama-recipes/pull/487

**Comment by KeitaW** [comment]
For reference: https://github.com/pytorch/pytorch/issues/104187

**Pull request merged**
