### PR TITLE
Add fsdp and smpv2 example for EKS

### PR DESCRIPTION
**Pull request by iankouls-aws**
*Issue #, if available:*

*Description of changes:*

The FSDP example launches Llama2 7b fully sharded data parallel distributed training on the huggingface c4 dataset.
The smpv2 example launches SageMaker ModelParallel Llama2 7b distributed training on HyperPod EKS.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by iankouls-aws** [comment]
@aruncs2005, could you please review the smpv2 examaple in this PR?

**Comment by aruncs2005** [comment]
looks good to me.

**Comment by iankouls-aws** [comment]
@shimomut pls review

**Comment by shimomut** [comment]
looks good to me.

**Review by shimomut — APPROVED** [review]
Looks good to me.

**Pull request merged**
