### PR TITLE
FSDP with meta device requires sync_module_states=True

### PR DESCRIPTION
**Pull request by pbelevich**
otherwise loss doesn't drop while training

### CODE REVIEW

**Comment by nghtm** [comment]
Code changes look minor, no breaking changes. 

Pavel - can you confirm the testing environment your performed for these changes? p5s?

**Comment by pbelevich** [comment]
> Code changes look minor, okay to merge as long as this has been tested
> 
> Pavel - can you confirm the testing environment your performed for these changes? p5s?

Confirmed, it's p5

**Review by nghtm — APPROVED** [review]
Approved without testing as changes are minor. Pavel - can you provide detail on the test environment you used for these code changes?

**Comment by perifaws** [comment]
Merged :)

**Pull request merged**
