### PR TITLE
Update efa-cheatsheet.md

### PR DESCRIPTION
**Pull request by sean-smith**
Add information on `NCCL_SOCKET_IFNAME`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by KeitaW — COMMENTED** [review]
I got the following from pcluster...

```
(base) ubuntu@p5-st-p5-1:~$ ifconfig 
...
enp105s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 10.1.46.161  netmask 255.255.128.0  broadcast 10.1.127.255
        inet6 fe80::14ca:49ff:fecc:33e3  prefixlen 64  scopeid 0x20<link>
        ether 16:ca:49:cc:33:e3  txqueuelen 1000  (Ethernet)
        RX packets 34982  bytes 1692318 (1.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 36084  bytes 2058025 (2.0 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
...
```

**Comment by cfregly** [comment]
double-checking:  i thought `enp` is for p5 and `ens` is for p4de.  (opposite of what's in this PR).  please confirm when you get a chance.  thanks!

**Comment by verdimrc** [comment]
You can use just `en` to cover both instance types.

**Comment by sean-smith** [comment]
Updated to `en` to cover both cases.

**Review by mhuguesaws — APPROVED** [review]
LGTM

**Pull request merged**
