### PR TITLE
Head node and login node ip in motd

### PR DESCRIPTION
**Pull request by sean-smith**
image

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nghtm** [comment]
"You are on the controller" but we then say "Head node IP". Lets be consistent in naming convention, ie controller or head

**Comment by nghtm** [comment]
otherwise, approving

**Review by nghtm — APPROVED** [review]
approved, left comments

**Comment by sean-smith** [comment]
> "You are on the controller" but we then say "Head node IP". Lets be consistent in naming convention, ie controller or head

Updated to "Controller"

**Pull request merged**
