### PR TITLE
Adding the CF template for FSx Lustre for HyperPod EKS workshop

### PR DESCRIPTION
**Pull request by shimomut**
*Description of changes:*

Starting to maintain the CloudFormation template for FSx Lustre in this repository.
This template is used in the HyperPod EKS workshop - FSxL static provisioning section (https://catalog.workshops.aws/sagemaker-hyperpod-eks/en-US/01-cluster/06-fsx-for-lustre#static-provisioning-(optional)).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mhuguesaws** [comment]
What's the value compare to https://github.com/aws-samples/awsome-distributed-training/blob/main/1.architectures/5.sagemaker-hyperpod/3.FSxLustre.yaml ?

**Review by mhuguesaws — COMMENTED** [review]
What's the value compare to existing material in the repo?
Why not changing/updating existing?

**Comment by shimomut** [comment]
Didn't pay enough attention to the existing template for HyperPod Slurm, but checking it now.

**Comment by shimomut** [comment]
The [existing FSxL template for HyperPod Slurm](https://github.com/aws-samples/awsome-distributed-training/blob/main/1.architectures/5.sagemaker-hyperpod/3.FSxLustre.yaml) has a dependency to "[2.SageMakerVPC.yaml](https://github.com/aws-samples/awsome-distributed-training/blob/main/1.architectures/5.sagemaker-hyperpod/2.SageMakerVPC.yaml)", and referring to the Subnet and Security Group created by the 2.SageMakerVPC.yaml.

``` yaml
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${NetworkStack}-SecurityGroup"
      SubnetIds:
        - Fn::ImportValue:
            !Sub "${NetworkStack}-PrivateSubnet"
```

We could change this existing template to support both HyperPod Slurm and HyperPod EKS by stopping importing these values, and letting customers manually specify the values. Does it seem like a good plan ? @mhuguesaws

**Comment by mhuguesaws** [comment]
Yes let's minimize duplication.

**Comment by shimomut** [comment]
Got it, I am withdrawing this PR, and will work on a separate one to reuse existing template.

**Pull request closed without merging**
